version: 2.1
orbs:
  aws-serverless: circleci/aws-serverless@1.0.2
jobs:
  build-and-test:
    executor: aws-serverless/default
    steps:
      - checkout
      - run: node --version
workflows:
    build-and-test:
      jobs:
        - build-and-test