version: 2.1
orbs:
  aws-serverless: circleci/aws-serverless@1.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd api/hello-world && npm install
      - run: cd api/hello-world && npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test